export const acceptedLeads = [
  {
    id: 1000001,
    contactFirstName: "Bob",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 3",
    location: "Carramar 6031",
    category: "Painter",
    description: "Sample description for accepted lead 1",
    price: "200.00",
    contactFullName: "contactFullName",
    contactno: "12345",
    email: "some@mailnator.com",
    leadType: "Lead Invitation",
  },
  {
    id: 1000002,
    contactFirstName: "Alice",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 4",
    location: "Perth 6000",
    category: "Electrician",
    description: "Sample description for accepted lead 2",
    price: "150.00",
    contactFullName: "contactFullName",
    contactno: "54321",
    email: "another@mailnator.com",
    leadType: "Lead Invitation",
  },
  {
    id: 1000003,
    contactFirstName: "Charlie",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 5",
    location: "Fremantle 6160",
    category: "Plumber",
    description: "Sample description for accepted lead 3",
    price: "180.00",
    contactFullName: "contactFullName",
    contactno: "98765",
    email: "third@mailnator.com",
    leadType: "Lead Invitation",
  },
  {
    id: 1000004,
    contactFirstName: "David",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 6",
    location: "Joondalup 6027",
    category: "Carpenter",
    description: "Sample description for accepted lead 4",
    price: "220.00",
    contactFullName: "contactFullName",
    contactno: "67890",
    email: "fourth@mailnator.com",
    leadType: "Lead Invitation",
  },
  {
    id: 1000005,
    contactFirstName: "Eve",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 7",
    location: "Rockingham 6168",
    category: "Landscaper",
    description: "Sample description for accepted lead 5",
    price: "250.00",
    contactFullName: "contactFullName",
    contactno: "54321",
    email: "fifth@mailnator.com",
    leadType: "Lead Invitation",
  },
  {
    id: 1000006,
    contactFirstName: "Frank",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 8",
    location: "Armadale 6112",
    category: "Roofing",
    description: "Sample description for accepted lead 6",
    price: "280.00",
    contactFullName: "contactFullName",
    contactno: "12345",
    email: "sixth@mailnator.com",
    leadType: "Lead Invitation",
  },
  {
    id: 1000007,
    contactFirstName: "Grace",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 9",
    location: "Midland 6056",
    category: "Handyman",
    description: "Sample description for accepted lead 7",
    price: "160.00",
    contactFullName: "contactFullName",
    contactno: "98765",
    email: "seventh@mailnator.com",
    leadType: "Lead Invitation",
  },
  {
    id: 1000008,
    contactFirstName: "Hank",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 10",
    location: "Kalamunda 6076",
    category: "Tiler",
    description: "Sample description for accepted lead 8",
    price: "210.00",
    contactFullName: "contactFullName",
    contactno: "67890",
    email: "eighth@mailnator.com",
    leadType: "Lead Invitation",
  },
  {
    id: 1000009,
    contactFirstName: "Ivy",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 11",
    location: "Wanneroo 6065",
    category: "Painter",
    description: "Sample description for accepted lead 9",
    price: "190.00",
    contactFullName: "contactFullName",
    contactno: "54321",
    email: "ninth@mailnator.com",
    leadType: "Lead Invitation",
  },
  {
    id: 1000010,
    contactFirstName: "Jack",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 12",
    location: "Baldivis 6171",
    category: "Electrician",
    description: "Sample description for accepted lead 10",
    price: "170.00",
    contactFullName: "contactFullName",
    contactno: "12345",
    email: "tenth@mailnator.com",
    leadType: "Lead Invitation",
  },
];




export const invitedLeads = [
  {
    id: 1000011,
    contactFirstName: "Bob",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 3",
    location: "Carramar 6031",
    category: "Painter",
    description: "Sample description for accepted lead 1",
    price: "200.00",
    contactFullName: "contactFullName",
    contactno: "0412345678",
    email: "some@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: true,
  },
  {
    id: 1000012,
    contactFirstName: "Alice",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 4",
    location: "Perth 6000",
    category: "Electrician",
    description: "Sample description for accepted lead 2",
    price: "150.00",
    contactFullName: "contactFullName",
    contactno: "0423456789",
    email: "another@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: false,
  },
  {
    id: 1000013,
    contactFirstName: "Charlie",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 5",
    location: "Fremantle 6160",
    category: "Plumber",
    description: "Sample description for accepted lead 3",
    price: "180.00",
    contactFullName: "contactFullName",
    contactno: "0434567890",
    email: "third@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: true,
  },
  {
    id: 1000014,
    contactFirstName: "David",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 6",
    location: "Joondalup 6027",
    category: "Carpenter",
    description: "Sample description for accepted lead 4",
    price: "220.00",
    contactFullName: "contactFullName",
    contactno: "0445678901",
    email: "fourth@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: true,
  },
  {
    id: 1000015,
    contactFirstName: "Eve",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 7",
    location: "Rockingham 6168",
    category: "Landscaper",
    description: "Sample description for accepted lead 5",
    price: "250.00",
    contactFullName: "contactFullName",
    contactno: "0456789012",
    email: "fifth@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: false,
  },
  {
    id: 1000016,
    contactFirstName: "Frank",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 8",
    location: "Armadale 6112",
    category: "Roofing",
    description: "Sample description for accepted lead 6",
    price: "280.00",
    contactFullName: "contactFullName",
    contactno: "0467890123",
    email: "sixth@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: true,
  },
  {
    id: 1000017,
    contactFirstName: "Grace",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 9",
    location: "Midland 6056",
    category: "Handyman",
    description: "Sample description for accepted lead 7",
    price: "160.00",
    contactFullName: "contactFullName",
    contactno: "0478901234",
    email: "seventh@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: false,
  },
  {
    id: 1000018,
    contactFirstName: "Hank",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 10",
    location: "Kalamunda 6076",
    category: "Tiler",
    description: "Sample description for accepted lead 8",
    price: "210.00",
    contactFullName: "contactFullName",
    contactno: "0489012345",
    email: "eighth@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: true,
  },
  {
    id: 1000019,
    contactFirstName: "Ivy",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 11",
    location: "Wanneroo 6065",
    category: "Painter",
    description: "Sample description for accepted lead 9",
    price: "190.00",
    contactFullName: "contactFullName",
    contactno: "0490123456",
    email: "ninth@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: false,
  },
  {
    id: 1000020,
    contactFirstName: "Jack",
    dateCreated: "2023-11-03",
    suburb: "Sample Suburb 12",
    location: "Baldivis 6171",
    category: "Electrician",
    description: "Sample description for accepted lead 10",
    price: "170.00",
    contactFullName: "contactFullName",
    contactno: "0498765432",
    email: "tenth@mailnator.com",
    leadType: "Lead Invitation",
    isAccepted: true,
  },
];


